easy_admin:
    site_name: 'FABINI Admin'
    entities:
        Product:
            class: App\Entity\Product
            form:
                fields:
                - articleId
                - articleName
                - price
                - title
                - description
                #- { property: 'imageFile', type: 'vich_image', type_options: { required: true } }
                - { property: 'images', type: 'collection' , type_options: { entry_type: 'App\Form\ImageType' } }

