easy_admin:
    site_name: 'FABINI Admin'
    entities:
        Mimo:
            class: App\Entity\Mimo
            form:
                fields:
                - title
                #- { property: 'imageFile', type: 'vich_image', type_options: { required: true } }
                - { property: 'images', type: 'collection' , type_options: { entry_type: 'App\Form\ImageType', by_reference: false } }
