vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /images/uploads
            upload_destination: '%kernel.project_dir%/public/images/uploads'
            namer: vich_uploader.namer_uniqid
