#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }


root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /de
        permanent: true

index:
    path: /{_locale}
    defaults:
        _controller: 'App\Controller\IndexController::index'
    requirements:
        _locale: "%supported_languages%"